wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1718306507
    t:
      1:
      - 15
      - 55
      - 105
      3:
      - 23
      4: 3.10.14
      5: 0.17.0
      8:
      - 3
      - 5
      - 9
      13: windows-amd64
