wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.16.6
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1718453622.0
    t:
      1:
      - 15
      - 55
      - 105
      2:
      - 5
      - 15
      - 53
      - 54
      - 55
      - 105
      3:
      - 23
      4: 3.11.7
      5: 0.16.6
      8:
      - 3
      - 5
      - 9
      13: windows-amd64
    framework: sklearn
